In [ ]:
Question 1
Write a Python program using a for loop that iterates from 5 to 30 and adds 2 to each number. Print the result for each loop.
                                                                                                              

In [1]:
import numpy as np

In [3]:
# A program that iterates from 5 to 30, adding 2 to each using FOR LOOP

for num in range(5,30,2):
    print(num)

5
7
9
11
13
15
17
19
21
23
25
27
29


In [ ]:

Question 2
Given a variable x = 5, write a Python program using a while loop that checks if x <= 55 and increment x by 5 if True. For each iteration print the value of x.

In [5]:
# A program that returs a result for a variable as long as the condition is true using WHILE LOOP

x = 5
while x <= 55:
    print(x)
    x +=5
    print(x)

5
10
10
15
15
20
20
25
25
30
30
35
35
40
40
45
45
50
50
55
55
60


In [ ]:
Question 3
Write a function in Python that accepts a list of integers and returns a NumPy array containing these integers. Show how you would call this function with the list [67, 43, 56, 43, 46].

In [7]:
# Returning a list of integer as an array:

int = [67,43,56,43,46]
    
np.array(int)

array([67, 43, 56, 43, 46])

In [22]:
# showing how the function will be called on

def calus(num_1,num_2,num_3,num_4,num_5):
    int = 67,43,56,43,46
    return int

### **Question 4**

 Demonstrate how to create a 1-dimensional, 2-dimensional, and 3-dimensional numpy arrays using `np.array`. Use any suitable data for the arrays and display each. The 1 dimensional, 2 dimensional and 3 dimensional arrays you created should have shapes of ```(7,), (4, 4), and (3, 2, 3)``` respectively. Print out the shapes of each array after you have created them.

In [24]:
# Demonstrating how to create and print 1,2,3-dimensional arrays

# 1-dimensional array of (7,)
num_1 = ([1,
         2,
         3,
         4,
         5,
         6,
         7])
np.array(num_1)

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
# 2-dimensional array of (4,4)

num_2 = ([[1,2,3,4],
         [1,2,3,4],
         [1,2,3,4],
         [1,2,3,4]])
np.array(num_2)
#my_array2 = np.array(num_2)
#print(my_array2

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [28]:
# 3-dimensional array of (3,2,3)

num_3 = ([[1,2,3],
         [1,2,3]],

         [[1,2,3],
         [1,2,3]],

         [[1,2,3],
          [1,2,3]])

np.array(num_3)

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [30]:
# shape of the 1-dimensional array above
my_array1 = np.array(num_1)
my_array1.shape

(7,)

In [32]:
# shape of the 2-dimensional array above
my_array2 = np.array(num_2)
my_array2.shape

(4, 4)

In [34]:
# shape of the 3-dimensional array above
my_array3 = np.array(num_3)
my_array3.shape

(3, 2, 3)

In [ ]:

Question 5
5a. Write a Python code to create two arrays using np.zeros and np.ones with a shape of (4, 5). Print both arrays.
5b. Using the np.arange function, create an array from 10 - 36
5c. Generate a numpy array with 25 linearly spaced values ranging from 20 to 50 using np.linspace. Print the array.

In [36]:
# python code of arrays using np.zeros and np.ones

# Using np.zeros

np.zeros((4,5))
my_list = np.zeros((4,5))
print(my_list)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
# Using np.ones

np.ones((4,5))
my_list = np.ones((4,5))
print(my_list)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
# Creating an array of 10 to 36 using np.arange

np.arange(10,36)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35])

In [42]:
# Generating a linearly spaced array of 25 values

np.linspace(20,50,25)
my_array = np.linspace(20,50,25)
print(my_array)

[20.   21.25 22.5  23.75 25.   26.25 27.5  28.75 30.   31.25 32.5  33.75
 35.   36.25 37.5  38.75 40.   41.25 42.5  43.75 45.   46.25 47.5  48.75
 50.  ]
